### ISSUE TITLE
zap v11 crash?

### ISSUE THREAD

**Issue by mschoch** [blevesearch/zap#28]
This was reported on gitter:

```
package main

import (
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/index/scorch"
)

func main() {

	mapping := bleve.NewIndexMapping()
	index, err := bleve.NewUsing("hello.bleve", mapping, scorch.Name, scorch.Name, nil)

	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	batch := index.NewBatch()

	fmt.Println("start batch indexing....")

	for i := 0; i < 1000000; i++ {
		data := make(map[string]interface{})
		data["name"+strconv.Itoa(i)] = "TestName" + strconv.Itoa(i)
		data["age"+strconv.Itoa(i)] = i

		batch.Index("d"+strconv.Itoa(i), data)

		if batch.Size() > 1000 {
			// fmt.Println("Start Batched")
			err = index.Batch(batch)
			if err != nil {

				fmt.Println("Index ", i)
				panic(err)
			}
			batch = index.NewBatch()
			// fmt.Println("Batched")

		}
	}

	if batch.Size() > 0 {
		err = index.Batch(batch)
		if err != nil {
			panic(err)
		}

	}

	fmt.Println("Finish")
	// Calling Sleep method
	time.Sleep(1 * time.Minute)

	// Printed after sleep is over
	fmt.Println("Sleep Over.....")

}
```

Results in:

```
start batch indexing....
panic: runtime error: index out of range [-1]

goroutine 25 [running]:
github.com/blevesearch/zap/v11.mergeStoredAndRemap.func2(0xc001483130, 0x9, 0x74, 0xc01181aeab, 0xc, 0xc, 0x0, 0x0, 0x0, 0x1)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/merge.go:687 +0x579
github.com/blevesearch/zap/v11.(*SegmentBase).visitDocument(0xc0083ca000, 0xc00041baa0, 0x1287, 0xc00038f618, 0x19, 0x0)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/segment.go:384 +0x383
github.com/blevesearch/zap/v11.mergeStoredAndRemap(0xc007a80c80, 0xa, 0xa, 0xc007a80c30, 0xa, 0xa, 0xc004103380, 0xc016700000, 0x271a2, 0x271a2, ...)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/merge.go:685 +0x47f
github.com/blevesearch/zap/v11.MergeToWriter(0xc007a80c80, 0xa, 0xa, 0xc007a80c30, 0xa, 0xa, 0x400, 0xc004103350, 0xc00c0cd5c0, 0x203001, ...)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/merge.go:132 +0x1ef
github.com/blevesearch/zap/v11.mergeSegmentBases(0xc007a80c80, 0xa, 0xa, 0xc007a80c30, 0xa, 0xa, 0xc013fcfe90, 0x22, 0xc000000400, 0xc00c0cd5c0, ...)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/merge.go:79 +0x24c
github.com/blevesearch/zap/v11.(*ZapPlugin).Merge(0xfd0548, 0xc013f9ae60, 0xa, 0xa, 0xc007a80c30, 0xa, 0xa, 0xc013fcfe90, 0x22, 0xc00c0cd5c0, ...)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/zap/v11@v11.0.9/merge.go:54 +0x14f
github.com/blevesearch/bleve/index/scorch.(*Scorch).planMergeAtSnapshot(0xc0002c2000, 0xb68640, 0xc0000c2040, 0xc00030a000, 0xc00e8d4e00, 0x0, 0x0)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/bleve@v1.0.9/index/scorch/merge.go:321 +0xad9
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0002c2000)
        /home/mandeep/work/pkg/mod/github.com/blevesearch/bleve@v1.0.9/index/scorch/merge.go:68 +0x2c7
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
        /home/mandeep/work/pkg/mod/github.com/blevesearch/bleve@v1.0.9/index/scorch/scorch.go:206 +0x125
exit status 2
```

I was able to reproduce the problem locally.

**Comment by mschoch** [comment]
Ah I see the problem now.  Bleve only supports 2^16 fields, your code creates more than that.
